### ISSUE TITLE
Top of navbar is clipped in mobile and cannot scroll up

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1068]
On android I cannot scroll up in the navbar and 'Chapters' isn't visible. 

**Browser**: Samsung Internet v9.2.10.15
**Operating System**: Android v9
**Device**: Samsung Galaxy S9

Another team member also experiences this in Safari on iOS. Seems to be working fine in Chrome on mobile. 

![rsz_1screenshot_20190702-071158_samsung_internet](https://user-images.githubusercontent.com/16066822/60472383-c8e8de80-9cbc-11e9-9b85-45de1c42d528.jpg)

**Comment by eAlasdair** [comment]
My phone is an Oppo running android and there's no problem with the menu on chrome, however the problem **does exist** with my phone's default browser

**Comment by courtneycb** [comment]
Can confirm @eAlasdair's comment on my phone. I will ask what browser was used on iPhone.

**Comment by courtneycb** [comment]
iPhone browser used was safari.

**Comment by JackMorganNZ** [comment]
Unless it has been modified, it would be worth searching Bootstrap issues for this problem, otherwise it needs to be reported to them. It's a serious issue, but might be a custom style of ours breaking it.

**Comment by eAlasdair** [comment]
A slightly related issue is that the internetnz logo overlaps the red `check out CSU` bar on my phone's base browser

**Comment by JackMorganNZ** [comment]
> A slightly related issue is that the internetnz logo overlaps the red `check out CSU` bar on my phone's base browser

That is really weird, can you make a new issue for that, with a screenshot, browser info?

**Comment by eAlasdair** [comment]
Some observations:

- There is no real mention of this issue anywhere from what I could find. However I did find a [comment](https://github.com/twbs/bootstrap/issues/11415#issuecomment-28080288) indicating that Bootstrap 3 does not officially support the default Android browser (not sure about BS4)
- It appears that the navbar expands both up and down, with the third field (curriculum guides) being positioned in the center.
  - By setting `$navbar-height` (in `_core-variables.scss`) to 10rem you can see that the dropdown does indeed center itself in relation to the button (and at this height 'chapters' can be clicked on, but it looks silly)
- [Here](https://jsbin.com/yakutamome/edit?html,output) is a code snippet approximating the state of the website without all the fluff (the ul & li tags instead of div and a tags make no difference).
  - The issue does not manifest with this example, indicating that it is an issue on our side, rather than with Bootstrap

**Comment by eAlasdair** [comment]
This page suggests that BS4 is supported
https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/

And later down suggests that the stock Android browser itself causes problems
https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/#android-stock-browser
this could be part of the issue

**Comment by courtneycb** [comment]
Resolved via #1104
