### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by MauricioLanda** [uccser/cs-field-guide#1085]
## Description

I would like to actively help on the spanish translation for the website if there is a need for it, i have seen that there is a lot of information not translated and having it in spanish would be very helpful for a lot of people that their first language is spanish or self-learners of the CS community

If yes, i would open a new branch so there is no conflicts and progressively start/work on it on my free time

**Comment by eAlasdair** [comment]
Thank you for your offer to help out, your work would be greatly appreciated!

We use a platform called Crowdin for our translations. The [CSFG Project](https://crowdin.com/project/cs-field-guide) is public so anyone is free to contribute. The [translation page of our documentation](https://cs-field-guide.readthedocs.io/en/latest/author/translations.html) goes into more detail about Crowdin, the translation pipeline, and some specific notes about translating Field Guide content.

Apologies for the inconvenience but, as we have formalised the translation pipeline, we ask that you please use Crowdin rather than opening a new branch.

Thanks again for your offer to contribute, please add any comments/questions you may have about it to this issue.

**Comment by eAlasdair** [comment]
Although it is closed, please feel free to comment on this issue with questions

**Comment by MauricioLanda** [comment]
I'm sorry for answering late, sure i will be working on it on my free tiem then, thanks
