### ISSUE TITLE
Bits cannot be flipped in Colour Matcher interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1166]
In the Colour Matcher interactive, you should be able to click the bit values to flip a bit value (as suggested by the description). However this doesn't occur.

![image](https://user-images.githubusercontent.com/8001048/66877788-6d482400-f013-11e9-955e-790b518e4adc.png)

Tried in:
- Google Chrome 77.0.3865.120
- Microsoft Edge 44.18362.387.0

**Comment by eAlasdair** [comment]
Works fine in Chrome 75.0.3770.100 and Firefox 67.0.4

**Comment by eAlasdair** [comment]
Okay I figured it out.

The function `updateSlidersFromRepresentation` sets each of the 6 nouisliders individually, one after the other, without regard for which slider/binary representation for the slider actually changed.
The function `update[num]bitPanel` sets the binary representation based on all three sliders, not based on each one individually.

This was adequate, but recently the nouislider `update` trigger was [bound to the `update[num]bitPanel` function](https://github.com/uccser/cs-field-guide/commit/694617bb8090a19698b4bbf23d1ebb1c1ac36162#diff-4bd3a9256648a3f6013715f3c7620c74R142). This means a change in any one slider affects all of the binary representation

So what happens is:
- The user clicks a bit in the representation
- The bit successfully flips
- The red nouislider is updated (`updateSliderFromRepresentation` step 1 or 5)
- The binary representation is set to the values of the nouisliders (`update` trigger)
  - If the flipped bit was not red, this reflips it because the respective slider hasn't been updated
- The green nouislider is updated (`updateSliderFromRepresentation` step 2 or 6)
- And so on

**Comment by JackMorganNZ** [comment]
Impressive work @eAlasdair!
