### ISSUE TITLE
Image links not working

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#129]
Image links are not working correctly. I am certain that it is not a file name issue, as the image appears correctly if the link is removed.

```[{image filename="software-engineering/xkcd-the-general-problem.png"}](http://xkcd.com/974/)```

This is following the syntax in the writing text guide.

**Comment by Heidirose** [comment]
@Marcus-SK This is what I was talking about

**Comment by Marcus-SK** [comment]
The issue is that the [link] regex is parsed before the [image] regex, instead of the other way around.

However, applying that as a quick fix means the 'image link' feature and the image zoom feature clash.
(When clicking on an image, it zooms weirdly before redirecting to the link)

We need to discuss whether 'image links' are useful, or if they should be replaced by some other feature, like captions below an image that could contain an external link to the image source.  

For now, let's just leave it as is (i.e. not use image links)

**Comment by JackMorganNZ** [comment]
The syntax @Heidirose used at the top was the original intention at used to work before we used MaterializeCSS. However Marcus brings up a great point on possible solutions. Enlarging an image is important over a link, and should remain consistent with all other images.

I propose we use @Marcus-SK's solution and extend it, and have the following arguments for images:

- `caption` - Adds the text below the image
- `caption-link` - Creates a link on the caption text to the given address
- `source` - Adds a text word "Source" with a link to the given address

I think this allows us to create images and use them in the largest variety of situations. The only time I can think of that can't be used with this system, is a image to a website we want people to visit with the image being the link. However I don't think an image should be used in this situation (as websites change). A normal link should be used instead (or we can develop a button for the link if it needs to stand out).

Keen to hear your thoughts before I start programming it.
