### ISSUE TITLE
Updates to equation-builder interactive

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#1377]
- [x] Title should be "Context-free Grammar Challenge" rather than "Context-free Grammar Equation Builder". 
  - [x] Old URL should redirect to new URL
- [x] When choosing a new challenge using the Random/Simple/Next button, it should also reset.
- [x] The following should only generate examples with "a" and "b" in them, but clicking "Random" or "Simple" occasionally adds digits to the target string!`
[.../interactives/cfg-equation-builder/?productions=S:'a' S 'b'|'ab'&examples=ab|aabb|aaaabbbb|aaaaaabbbbbb](https://csfieldguide.org.nz/en/interactives/cfg-equation-builder/?productions=S:%27a%27%20S%20%27b%27|%27ab%27&examples=ab|aabb|aaaabbbb|aaaaaabbbbbb)
- [x] The production for N is confusing (0-9) as it uses a regex with what looks like a minus sign in it. We could explore changing it to `N -> 0|1|2|3|4|5|6|7|8|9`
- [x] Would be great to show the history of the productions chosen in the activity. It could be anything from a scrolling list of the productions chosen, through to a full parse tree.

**Comment by eAlasdair** [comment]
> The following should only generate examples with "a" and "b" in them, but clicking "Random" or "Simple" occasionally adds digits to the target string!`
.../interactives/cfg-equation-builder/?productions=S:'a' S 'b'|'ab'&examples=ab|aabb|aaaabbbb|aaaaaabbbbbb

This is a limitation mentioned in the [README](https://github.com/uccser/cs-field-guide/tree/develop/csfieldguide/static/interactives/cfg-parsing-challenge#advanced-parameters): `recursion-depth` needs to be set higher, with `retry-if-fail` set to `true`
- For example: [.../interactives/cfg-equation-builder/?productions=S:'a' S 'b'|'ab'&recursion-depth=5&retry-if-fail=true&examples=ab|aabb|aaaabbbb](https://csfieldguide.org.nz/en/interactives/cfg-equation-builder/?productions=S:%27a%27%20S%20%27b%27|%27ab%27&recursion-depth=5&retry-if-fail=true&examples=ab|aabb|aaaabbbb|aaaaaabbbbbb) will never put numbers in, and is very unlikely to fail through too much recursion

> The production for N is confusing (0-9) as it uses a regex with what looks like a minus sign in it. We could explore changing it to `N -> 0|1|2|3|4|5|6|7|8|9`

I chose X-Y for its second meaning as `numbers X through Y` because `N -> 0`, `N -> 1`, etc was far too tall and `N -> 0|1|2|3|4|5|6|7|8|9` is likely too wide for the box that it's in. Improvements could definitely still be explored though

**Comment by eAlasdair** [comment]
>  Title should be "Context-free Grammar Challenge" rather than "Context-free Grammar Equation Builder".
Old URL should redirect to new URL

The name has already been changed to `CFG Parsing Challenge` on develop as of at least February, unsure if the redirection has been done
