### ISSUE TITLE
Issues with formatting when using glossary commands

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#174]
In the Formal languages chapter, there are glossary definitions for "alphabet", "transition", "string" etc.... later in the paragraph the asterisks around *language* are ignored, and the following paragraphs are run on until it reaches the {image} command. I've played with a few things, and it seems to be due to the glossary commands - they seem to take it into a new mode?

**Comment by timbellnz** [comment]
...although this doesn't happen earlier in the chapter in a jargon-buster panel ("People working with formal languages usually use Finite State *Automata*" is formatted correctly.)

**Comment by timbellnz** [comment]
And perhaps related, having only a glossary-link on a line seems to create a new paragraph e.g. from formal languages:

put together a
{glossary-link term="string"}string{glossary-link end}
of letters,

**Comment by JackMorganNZ** [comment]
This is a tricky one, mostly due to the wide array of use cases and the way Markdown is parsed.

See the following text:

```
The relationships between the main kinds of grammars was described by the linguist Noam Chomsky, and is often called the
{glossary-definition term="Chomsky Hierarchy" definition="A hierarchy of four classifications of formal languages, ranging from simple regular expressions to very flexible (but computationally difficult) grammars."}
{glossary-link term="Chomsky Hierarchy" reference-text="Formal languages"}Chomsky Hierarchy{glossary-link end}
after him.
```

The end result should be:

"The relationships between the main kinds of grammars was described by the linguist Noam Chomsky, and is often called the [Chomsky Hierarchy](#) after him."

When our parser encounters the `glossary-link`, it creates the relevant HTML and substitutes it with the text. It ignored any whitespace before or after, so the result after this first step would be (in HTML):

```
The relationships between the main kinds of grammars was described by the linguist Noam Chomsky, and is often called the
{glossary-definition term="Chomsky Hierarchy" definition="A hierarchy of four classifications of formal languages, ranging from simple regular expressions to very flexible (but computationally difficult) grammars."}
<span class="anchor-link"><a href="../further-information/glossary.html#chomsky-hierarchy" id="glossary-chomsky-hierarchy-2" class="glossary-anchor-link glossary-anchor-link-highlight">Chomsky Hierarchy</a></span>
after him.
```

The `glossary-definition` is then processed, substituting the text for HTML again. The main issue occurs when the normal Markdown tries to parse the combination of both text and HTML and decide where paragraph breaks are. After looking into the issues above, I've come up with several solutions.

Three points:

1. We will strip any whitespace from the end of our inserted HTML, which appears to please the Markdown parser into reading it as one paragraph.
2. Currently when a link is parsed to a glossary term that has no definition, it logs and error and returns an empty string of HTML. This will be changed to the original text so the output is still readable.
3. Old HTML from interactives in the original CSFG need to be removed ASAP as it ruins formatting from that point on in the chapter (this is why the world `language` wasn't being italicized).
