### ISSUE TITLE
xkcd links

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#200]
There are two xkcd cartoons in the formal languages chapter. One is just an image; the other attempts to hyperlink, but doesn't work:
{image filename="fl-xkcd-regular-expressions.png" alt="xkcd comment on regular expressions"}](http://xkcd.com/208/)

I've temporarily changed this to just an image.

The coding-encryption chapter has another format (image, then separate link).

Check the xkcd licence for what is required, to decide if we'll hyperlink, or just put the link in the permissions page, then make them consistent.

The chapters that use xckd will then need updating:
coding-encryption.html
complexity-tractability.html
formal-languages.html
human-computer-interaction.html
software-engineering.html

**Comment by JackMorganNZ** [comment]
The linking of images is now handled by a [new syntax documented here](https://github.com/uccser/cs-field-guide/blob/develop/docs/writing-text.md#images). The older syntax does not work now due to MaterializeCSS.

I will go through and update these images with the new syntax, and add the relevant permissions.
