### ISSUE TITLE
Numbering questions in a box

### ISSUE THREAD

**Issue by timbellnz** [uccser/cs-field-guide#299]
In the data representation chapter we have "1. Represent each character in your name using UTF-32.", which is part of a numbered list. However, the rendered version doesn't number the list (same for the next spoiler box).

**Comment by JackMorganNZ** [comment]
It appears the numbered list is being created correctly, however the CSS is overriding the numbers/bullet points within a panel (the panel itself is a list item where the bullet points are hidden).

I'll rewrite the CSS to display the numbers/points.

**Comment by JackMorganNZ** [comment]
This has been fixed, however I couldn't merge `develop` into `content/data-representation` as there was a merge conflict. I presume some text was deleted in the new branch but the old text has had typo fixes in `develop` since then.

An author (@Heidirose or @timbellnz) should merge `develop` into `content/data-representation` and resolve the merge conflict. If you need help with solving a conflict, let me know.

**Comment by Heidirose** [comment]
Done. fa509381813f3befecaeeb24e4ff4027fa11deef
