### ISSUE TITLE
Review needed: Positive and Negative numbers assessment guide

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#317]
This guide can be found in branch content/data-representation

With file path ...curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-numbers.md

(All of it was in commit 1f8b3074d2d86982655a3ec7da812858869e32f6)

**Comment by timbellnz** [comment]
Minor fixes/polishing done: commit fffdf7d5dd951cd46a317fc0872676f7d8e4cec5

**Comment by Heidirose** [comment]
Checked the review and satisfied with it (a couple of minor comments on the commit which I'd like you to give feedback on so that we can consider creating issues for them, but might not fix for 2.5).

**Comment by Heidirose** [comment]
Oh by the way @hayleyavw , it's great if you can read over this too. I just closed the issue because it is no longer essential to 2.5 (but would be very helpful).

**Comment by hayleyavw** [comment]
@timbellnz @Heidirose right so I finally got a chance to read this. Really well written, very clear, but I'm worried it's ....too helpful. I'm wondering if in the `Explaining reasons why Two's Complement is widely used, and simple sign bits are not` section we are spoon-feeding them a bit too much, particularly where we give them calculations to include. Could we somehow generalise these - give one or two calculations and why they are significant, then ask the student to find any other patterns themselves? As I was reading it, it just seemed like there was nothing left for me figure out. Or did we intentionally list exactly what we want since this section does not go to Excellence?
Feel free to argue with me on this one. Not essential for the 2.5 release.

**Comment by Heidirose** [comment]
My thoughts on the assessment guide were that it only goes to merit, and that it is only one of the two topics they need to cover for data representation. This assessment guide is a tiny part of the overall standard -- perhaps about 1/8 of the work at most, so half a credit.

Some students will have trouble with those concepts (e.g. with generalising base 10 column addition to base 2 column addition, etc). You found it easy, but I don't think most of them will. Just my thought. Will see what @timbellnz says.

**Comment by timbellnz** [comment]
My thoughts ranged over what both of you said! I'll have another look at it as part of this issue, and if I'm still feeling ambivalent, we could ask an experienced teacher for an opinion. I think it's fine to release it as it is, and it would also be fine to dial back the help a bit, but I'll review it to see if it's more obvious what to do. (So this issue remains assigned to me until I do that!)

**Comment by Heidirose** [comment]
Awesome, thanks for that Tim! My thought also was that it is more abstract (and so more potentially confusing), will be useful to get a teacher's opinion. Can you do that as soon as possible? I'd prefer to get any modifications out before the guide is widely used.

**Comment by hayleyavw** [comment]
Yea good point @Heidirose, not sure if most students would find this easy or not. @timbellnz I would also be keen to get some feedback from a teacher.

**Comment by Heidirose** [comment]
Removing the milestone 2.5 tag, as we've agreed that while this is important, it's not required for 2.5 :)

**Comment by timbellnz** [comment]
I've checked over it; regarding difficulty, it seems about right. The guide does provide a lot of help, but the topic will be quite complex for a lot of students, and if they can do a correct worked example with their own numbers they'll be doing pretty well. I did a bit of polishing: commit 471aeb9709efb7e924a2fc9806515008f6f2c372
