### ISSUE TITLE
Provide printer-friendly view of chapters

### ISSUE THREAD

**Issue by oughter** [uccser/cs-field-guide#319]
Providing a stripped down view of chapter content would be helpful for those wanting a hard copy of chapters for studying for an exam or job interview.

Some ideas for the view:
* Would not include the left nav sidebar or right nav table of contents
* Would auto-expand the special sections like Curiosity, Challenge, Project, etc.
* A note would be included where an embedded video or interactive appears in the content

If you're open to this, I could work on implementing it -- it should be straightforward to do using CSS to show/hide content.

**Comment by JackMorganNZ** [comment]
This would be amazing, though I've already done some planning on this so if you can wait a day then I can get my notes from work. Would love to get this implemented (has been low priority for a while).

**Comment by oughter** [comment]
Sure, sounds good.

**Comment by JackMorganNZ** [comment]
Hi @oughter,

Finally got a moment to type some thoughts, firstly I need to explain our original generation system before I talk about the new plan. Feel free to ask any questions as this is quite rushed and I'm still learning these new topics (which you may be an expert on).

The current system is built for two modes, writing a website or writing to a PDF. We haven't fully finished the PDF generation (some work on branch `pdf-generator`) but the idea was to [output different HTML for web and PDF](https://github.com/uccser/cs-field-guide/blob/pdf-generator/generateguide.py#L57). For each type of item in the `markdown-section.py` there would be an `if/else` statement to output the right HTML depending on the mode. However your idea of a printer friendly mode solves many problems, including #279 and also PDF generation.

So using your idea: Instead of generating different HTML for each type, lets create one version of HTML and use CSS to hide/show them (as you suggested). 

I guess the easiest way would be a button that when clicked adds a class to the `<body>` and then have CSS rules that hide/show items depending on that class appearing. I have no idea if this is the best way (especially performance wise) so keen to hear your thoughts. This would also allow us to make PDF's easily as we can add the class to the `<body>` element during generation and get the proper rendering.

However I think we could also achieve the same goal (or maybe in combination of) with [CSS media types](https://developer.mozilla.org/en/docs/Web/CSS/@media#Media_types), which I think does the same thing (but in a way more professional manner). Found [this article](https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/) which may be useful, though we may want to handle links, images, etc differently.

This will require quite a lot of rewriting of both `generate-guide.py` and `markdown-section.py` but will give us an amazing result. I've got plenty of time later this week to investigate/help but Monday's is always packed. Keen to hear your thoughts and ideas.

Cheers,

Jack

**Comment by oughter** [comment]
Hi @JackMorganNZ, thanks for passing along your notes. My first idea on how to achieve this was to have the site create a PDF from the content using one of the PDF JS libraries out there. 

After giving it more thought I feel like simply providing a stripped down view and offloading the PDF generation onto the user's browser would be less complex and troublesome. Since browsers today can either save a page as a PDF natively or do so through the use of an extension, a printer-friendly view should make for a clean PDF if the user wants to create one. If they don't want a PDF but just want to print out a chapter, then all of the PDF generation implementation goes to waste for that user.

I like the approach that we've discussed where the DOM would contain the markup for the normal view and then also markup for a printer-friendly view that is hidden unless activated. Regarding performance, the additional content in the HTML document would have a negligible impact on the page load, and using a CSS class to toggle the view is a common approach that is performant especially when a single containing element is the target (DOM access is relatively expensive, so minimizing the number of accesses is advisable).

Using the print media type would be the standards compliant way to go. I think that a nice approach would be to have the generator always output styles for the normal and stripped down views and then controlling display through either a separate print stylesheet or different rules within the main stylesheet.

**Comment by JackMorganNZ** [comment]
Hi @oughter, I've closed this commit as I've added both PDF output (using the `-p` command), and also printable versions of webpages (open a chapter and view the print preview). The process was fairly straightforward and intuitive, but some things required a bit more hacking/short term solutions (especially links to glossary and internal references). 

We are extracting the generation system out of this repository by the end of this year into it's own Python Package, so hope to reorganise and refactor the process there.

I've attached the current version of the PDF if you wish to view it: [Computer Science Field Guide - Student Version.pdf](https://github.com/uccser/cs-field-guide/files/309946/Computer.Science.Field.Guide.-.Student.Version.pdf), a couple of extra points regarding the PDF:
- Page numbers for table of contents are currently not possible (library doesn't support them but is being investigated)
- Footnotes are currently not possible (library doesn't support them but is being investigated) however we can create an alternative ourselves
- There are already two known bugs (#351 and #356)

Thanks again for your help and advice, really helped making this happen.
