### ISSUE TITLE
Review translation and rotation box interactive

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#333]
Getting this ready for release, @JackMorganNZ could you please comment on this issue with any changes you want made. I'm unsure about the relative paths used for linking to files across different folders, can you test that it works on our system and if not, let me know what to change :) (Last folder restructure in commit https://github.com/uccser/cs-field-guide/commit/4827ff4ac7f0ae888828a8fc6daa5c75f5d86bcd)

**Comment by JackMorganNZ** [comment]
Here are some ideas for the interface from using both interactives:

- [ ] Entering 90 into the rotation interactive should turn the box 90 degrees (1:1 ratio). I currently like the ratio of numbers for the translation interactive, but we may want to make numbers on a similar scale (can chat about this in detail soon).
- [ ] Possibly try moving box on input change rather than pushing enter.
- [ ] Clicking submit without selecting anything causes an `TypeError`.
- [ ] Upon clicking submit (with correct sequence), this error is hit `script.js:452 Uncaught TypeError: scene.removeObject is not a function`.
- [ ] This message is logged to console, check if it can be removed (or is due to issue) `THREE.WebGLRenderer 74`.
- [ ] Possibly add restart button after successful ending.
- [ ] Generally enlarge the interface:
  - [ ] Change instruction font to not monospace for readability.
  - [ ] Increase button and input internal padding.
  - [ ] Possible put each input on a new line.
- [ ] Begin incorrect *shaking* as soon as submit button is clicked.
- [ ] Limit input boxes to 3 digits.

Interactive is looking amazing, will be the best one so far!

**Comment by hayleyavw** [comment]
I tested out moving the box on input rather than by pushing enter when I was making it, it made the interactive very confusing to use (particularly when dropping a place holder, e.g. 500 -> 50 and vice versa as it led to very sudden movement).

**Comment by hayleyavw** [comment]
`THREE.WebGLRenderer 74` is a feature of threejs for devs to see what version the page is using, and has been discussed in the threejs repo, where the general consensus was to leave it there. The typical user will not notice it, and a curious dev might appreciate it :)

**Comment by hayleyavw** [comment]
For "Limit input boxes to 3 digits" I set a (-360, 360) range. For the rotation interactive it takes mod 360 of the given input, and for the translation interactive -360/360 act as the lower/upper bound so any number outside of this range automatically gets changed to -360/360.

**Comment by hayleyavw** [comment]
Tidied up a couple more things  https://github.com/uccser/cs-field-guide/commit/e15584f907b0c827dbcc3fbc6af173132b760dcd
