### ISSUE TITLE
Lack of control of formatting in report structure guidance

### ISSUE THREAD

**Issue by Heidirose** [uccser/cs-field-guide#361]
Example here: http://www.csfieldguide.org.nz/en/curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-numbers.html#hints-for-success

Currently, it is impossible without using HTML to get rid of the bullet points (while keeping the indentation), and getting the non headings onto the lines immediately after the headings.

I would like to do this to make them clearer. It doesn't really make sense to use bullet points (but the indentation is important for showing structure), and it should be clearer what text is grouped with what headings.

I could use HTML in the mean time if this will take awhile.

**Comment by JackMorganNZ** [comment]
I agree it doesn't look great currently, but I think it would be best to convey this information by a diagram instead of text. I made a mock up of a possible design here: 

![computer science report structure for 2 44](https://cloud.githubusercontent.com/assets/8001048/16182355/377e6446-36f9-11e6-9b64-d00400ec7c41.png)

Thoughts? If you have another idea for how it could be displayed, a diagram/screenshot would be really useful.

**Comment by Heidirose** [comment]
It looks nice, although we'd need to auto generate it rather than make it images, because it will be different on every assessment guide (there is also supposed to be more information for the sub topic the assessment guide is about but I temporarily dropped that due to it being problematic in the formatting).

So if we can auto generate it so that it is easy for me to make for each guide, if not, then lets just stick with text.

**Comment by Heidirose** [comment]
No longer applicable
