### ISSUE TITLE
Link error in HCI chapter 

### ISSUE THREAD

**Issue by JonRodtang** [uccser/cs-field-guide#410]
## Description

There is some error with the HTML making some links display the tags and not emmbeding them in text "<a href='https://en.wikipedia.org/wiki/Fitts's_law'>Fitts's law </a>".
 It can be found in "4.5. The whole story!".

### Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the issue.*

- [ ] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [ ] I have applied relevant labels

If this is a code related issue, please include the following in your description:

- [ ] Steps to reproduce the behavior
- [ ] Which platform(s) and browser are you encountering the issue on
- [ ] The behavior you expect to see, and the actual behavior

**Comment by DrCuriosity** [comment]
Good catch, Jon. Looking at [S4.5](http://csfieldguide.org.nz/en/chapters/human-computer-interaction.html), it seems the problem is that the apostrophes in the Wikipedia URLs are interfering with the single quotes being used in the `<a href='...'>` tags when the [Markdown source file](https://github.com/uccser/cs-field-guide/blob/develop/text/en/chapters/human-computer-interaction.md) is rendered.

A quick fix would be to escape the apostrophe characters, like so:
* https://en.wikipedia.org/wiki/Fitts%27s_law
* https://en.wikipedia.org/wiki/Hick%27s_law
