### ISSUE TITLE
Some images are too large

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#454]
The pictures are currently HUGE

**Comment by eAlasdair** [comment]
custom html has already been written `csfieldguide/utils/custom_converter_templates/image.html`

**Comment by eAlasdair** [comment]
cusom css has already been written as `.img-container` in `csfieldguide/static/scss/website.scss` but the images are still huge under certain circumnsances

**Comment by eAlasdair** [comment]
- Images scale to fill most of the width of the screen, this is not inherently a bad thing because it suits some wide but not tall images such as the substitution cipher ones [here](https://cs-field-guide-dev.appspot.com/en/chapters/coding-encryption/substitution-ciphers/)
- However, on desktop screens, images (and videos) above a certain height practically fill the screen, such as the cartoons [here](https://cs-field-guide-dev.appspot.com/en/chapters/software-engineering/)
- We need a conditional, so that only images above a certain height are scaled to a more appropriate max width
- As far as I know, that can't be done in css
- The image template `csfieldguide/utils/custom_converter_templates/image.html` is an html file but is interpreted differently, so as far as I could find it doesn't allow JS of any form

**Comment by JackMorganNZ** [comment]
This was a topic we spent a lot of time on deciding how to solve for CS Unplugged, I can share our approaches when I return to work.

> * As far as I know, that can't be done in css

If I understand what you are asking for correctly, this can be done with CSS media queries.

**Comment by eAlasdair** [comment]
Current solution is to scale down the source images

**Comment by JackMorganNZ** [comment]
This task involves two steps:
- [ ] Checking image size (resolution)
- [ ] Checking image size (file size)

**Comment by eAlasdair** [comment]
None of the images are in the MBs (like #512)

Excluding ones associated with individual interactives, I checked all the images and only the top 4 largest are above 200kb:
- `compression-comparison.png` (540kb)
- `compressed-jpeg.png` (ironically) (441kb)
- `fruit-bowl-photo-with-canny-edge-detection.png` (215kb)
- `time-capsule.png` (206kb)

**Comment by eAlasdair** [comment]
Closing this issue as I believe it has been addressed. Reopen if further action is needed
