### ISSUE TITLE
Create content style guide

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-field-guide#578]
To establish rules for writing chapters, e.g. capitalisation in headings etc.

This will also require reviewing all converted chapters to check they meet these requirements.

**Comment by eAlasdair** [comment]
Suggestions to add to content style guide that I originally made in #980 - moved back to after 3.0 release. Mostly inspired by the conversation between Jack and Hayley in #570:

## Capitalisation

- [ ] Capitalise the first word of every title/heading/sentence/this is obvious so we may not need to say it
- [ ] Capitalise every word in a major title, i.e. `Network Communication Protocols` the chapter
- [ ] Capitalise only the first word per sentence in a lesser title or heading, i.e. the `The whole story!` chapter section
  - [ ] For this purpose, a colon, hyphen etc does count as the end of a sentence, i.e. `Analysis: What do we build?`
- [ ] Capitalise acronyms/abbreviations, i.e. `Transport layer protocols - TCP, UDP `
- [ ] If a heading includes a proper noun, capitalise it appropriately. Couldn't find a good example, something like a chapter section subheading: `Who was Ada Lovelace?`

## Separators

- [ ] Use a hyphen to hyphenate words, i.e. `Double-barrelled` words
- [ ] Use `&ndash;` (instead of a hyphen) to add supplemental information, i.e. `Do this &ndash; it does something!` (this doesn't work for titles, so just use a hyphen)

## Spelling

- [ ] Use New Zealand English, which for the most part is British English
- [ ] Consider linking to [that spelling guide I made ](https://github.com/uccser/uccser-extras/blob/master/english-spelling-guide.md) for specific examples for spelling

## Other

- [ ] If you are unsure, **be consistent**. Look for examples of how its used elsewhere and let us know if it's inconsistent or doesn't make sense

**Comment by JackMorganNZ** [comment]
Looks good to me!
