### ISSUE TITLE
Check if interactive thumbnails exist

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#919]
On branch refactor-complexity-and-tractability-chapter we had to remove the check for interactive thumbnails on line 30 in check_required_files.py as the tests on lines 121 and 160 in test_chapter_loader.py and test_chapter_sections_loader.py respectively were failing.

It is failing because Verto is configured for systems without multiple languages so it isn't putting the right file paths in (it is expecting one file path for all languages). We need to reconfigure Verto and put the tests back in.

It was only failing for the City Trip interactive as all of the old manually created thumbnails still existed under the old file path for other whole page interactives.

**Comment by eAlasdair** [comment]
For reference, this is the problem and it's been happening the whole time

- Note that the automatically generated thumbnails are store elsewhere, not with the interactive itself
- The compiler(?) reads through the markdown file, and finds a template for a whole page interactive
`{interactive slug=name type=whole-page}`
- Then it checks `name/img/thumbnail.png` and goes "yep, that exists alright"
- Then it goes to where the _generated_ thumbnails are stored, and loads that one

Inspect a thumbnail for it's image path and you'll find it's not `name/img/thumbnail.png` but look through the `./csfg update` logs and see `name/img/thumbnail.png` is the file that's missing when it fails

**Comment by eAlasdair** [comment]
In other words:

Issue: Unused preset interactive thumbnails are still required

Verto is configured to look for a thumbnail image on the path `[interactive-name]/img/thumbnail.png` when linking to a full-page interactive.
This file (for almost all interactives) is no longer used anywhere in the project, since we switched to automatically generated ones on the path `static/img/interactives/thumbnails/[language-code]/[interactive-name].png`
As such the file isn't needed.
But introducing new full-page interactives without this file (or removing this file from current full-page interactives) results in `./csfg update` failing because Verto can't find it.
The permanent solution is to reconfigure Verto.
The temporary solution is to either remove the tests (as has been done on the branch mentioned) and put them back in after the fix, or add a thumbnail file and remove it after the fix.

**Comment by JackMorganNZ** [comment]
Just want to clarify a point in your message @eAlasdair: Verto doesn't look for the thumbnail path, our system does based off data Verto gives it. What happens is that when Verto finds an interactive it adds the default thumbnail path (or the path provided in the optional argument) and adds the image file to the required files set in the VertoResult object. Our system then checks each of those files exist within the static files of the project. Subtle difference but worth noting.

The permanent solution involves:
- Reconfiguring Verto to have a conditional to add these images to the required files set (in progress).
- Removing the existing thumbnail image files, as they are never used.
- The tests for checking the finder is called for searching thumbnail images using the VertoResult object should be removed (as the files won't exist), and they won't be listed in the VertoResult object after the Verto changes (so they will still fail).
- A new test should be added to check that all interactives mentioned in a Makdown file do exist, because therefore the thumbnails should be made.
- A test should be made (if it doesn't exist) that all interactive thumbnails are created without errors.

There is already a test to ensure all interactives are passed to the thumbnail generator.

I should be able to complete the Verto changes this week, it's high on my priority list.

**Comment by eAlasdair** [comment]
Thanks, I attempted to describe what happens, but was a bit confused on how Verto does it

**Comment by courtneycb** [comment]
closed via https://github.com/uccser/verto/pull/377
